### ISSUE TITLE
Use parallel processing

### ISSUE THREAD

**Issue by AmirMahmood** [ChristianFeldmann/VTM#3]
I use VTM 9.3 but it's very very slow on my system. i want to enable parallel processing.
I have Ubuntu 16.04 with GCC 5.4.0, and "libomp-dev" is installed.
I build VTM with below commands:
`mkdir build`
`cd build`
`cmake .. `
`-DCMAKE_BUILD_TYPE=Release`
Is OpenMP enabled by default or i must set some flag when building?

Thanks.

**Comment by ChristianFeldmann** [comment]
Hi! 
This is just a fork of the official repo from the HHI (https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM). I am not the maintainer and can not answer your question. Please contact one of the VTM software coordinators: https://jvet.hhi.fraunhofer.de/

But I think (I also looked at this a few weeks back) you are out of luck. There are no parallelization features that you can easily enable.
